### ISSUE TITLE
The example of the use of NLayer is not precise

### ISSUE THREAD

**Issue by r2123b** [naudio/NLayer#11]
I think the example should be like the following

```
var fileName = "myMp3File.mp3";
var mpegFile = new MpegFile(filename);
int audioDataLength = (int)(mpegFile.Length/sizeof(float));
float[] samples = new float[audioDataLength ];
mpegFile.ReadSamples(samples, 0, audioDataLength);
```

**Comment by markheath** [comment]
The example shows how to read 1 second's worth of samples (or 0.5 seconds for stereo).

Your sample shows reading the entire file into memory, which may not always be desirable for very large files.

**Comment by r2123b** [comment]
Oh~That's why you set a constant as the array size. Thank you for your reply.
