### ISSUE TITLE
Support sample rate of 22500?

### ISSUE THREAD

**Issue by PuneetKohli** [naudio/NLayer#12]
We have audio files from Amazon Polly (Text to Speech) and it returns MP3s with a sampling rate of 22500. Is there a way to support this?

**Comment by ioctlLR** [comment]
The decoder should handle this properly.  Given no updates in 2 years, we'll assume the issue was resolved.

**Comment by PuneetKohli** [comment]
Not sure if it was resolved but I am no longer working on that project.
