### ISSUE TITLE
Fix license file

### ISSUE THREAD

**Issue by roncli** [naudio/NLayer#8]
The license file in the root directory got cut off at the top, so I can't tell what license is used (I'm guessing LGPL 2.1, but I'm no license expert). :)

**Comment by markheath** [comment]
good spot. It was originally LGPL, but some changes from @ioctlLR mean that we could possibly switch to something like MIT which would be nice. @ioctlLR can you confirm?

**Comment by ioctlLR** [comment]
That is correct. The only derived code is from a MIT licensed source (see
LayerDecoderBase.cs and LayerIIIDecoder.cs for details), and the rest is
mine or yours. I was thinking MSPL, but MIT works. Dual with LGPL is also
fine, if you'd like.

**Comment by markheath** [comment]
I think MIT would be a good choice. Seems like that's what Microsoft are using themselves now in preference to MSPL. Not sure there's much point dual licensing as it just adds to confusion.

If you're OK with it, I'll switch to MIT

**Comment by ioctlLR** [comment]
Go for it. :)

**Comment by markheath** [comment]
done :)
